# Generated by Django 3.1.7 on 2021-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('address', models.CharField(blank=True, max_length=122, null=True)),
                ('city', models.CharField(blank=True, max_length=122, null=True)),
                ('state', models.CharField(blank=True, max_length=122, null=True)),
                ('pincode', models.CharField(blank=True, max_length=122, null=True)),
                ('addhar', models.CharField(blank=True, max_length=122, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('firdescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
