# Generated by Django 3.1.7 on 2021-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0003_auto_20210427_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='addhar',
            new_name='Addhar',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='firdescription',
            new_name='Firdescription',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='img',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='pincode',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='fir',
            old_name='state',
            new_name='State',
        ),
    ]
