# Generated by Django 3.1.7 on 2021-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0007_auto_20210429_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='Status',
            field=models.CharField(default='Pending', max_length=122),
        ),
    ]
