# Generated by Django 3.1.7 on 2021-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0009_auto_20210429_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='FirId',
            field=models.CharField(default=5058, max_length=122),
        ),
    ]
