# Generated by Django 3.1.7 on 2021-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0010_fir_firid'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdetails',
            name='FirId',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='FirId',
            field=models.CharField(default=3054, max_length=122),
        ),
    ]
