# Generated by Django 3.1.7 on 2021-04-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0011_auto_20210429_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='FirId',
        ),
        migrations.RemoveField(
            model_name='statusdetails',
            name='FirId',
        ),
    ]
